version: '3.8'

services:
  nextjs:
    build:
      context: ./nextjs-app
    volumes:
      - ./nextjs-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - app-network

  php:
    build:
      context: ./php-api
    volumes:
      - ./php-api:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - app-network

  socketio:
    build:
      context: ./socket-server
    volumes:
      - ./socket-server:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    command: nodemon /app/server.js
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:




