version: '3.8'

services:
  nextjs:
    build:
      context: ./nextjs-app
    volumes:
      - ./nextjs-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production  # For production
      - DATABASE_URL=${DATABASE_URL}  # Add this for connecting to Railway's MySQL
    command: npm run build && npm run start
    networks:
      - app-network

  php:
    build:
      context: ./php-api
    volumes:
      - ./php-api:/var/www/html
    ports:
      - "8080:80"
    environment:
      - MYSQL_URL=${DATABASE_URL}  # Connect to Railway's MySQL
    networks:
      - app-network

  socketio:
    build:
      context: ./socket-server
    volumes:
      - ./socket-server:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    command: nodemon /app/server.js
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
